In [1]:
import julia
import numpy as np

In [8]:
a=np.array([1,4,5,np.NAN,33,5,np.NAN,5,8,np.NAN])
b=np.array([1,5,np.NAN,5,np.NAN,5,np.NAN,6,np.NAN,9])

In [9]:
a.shape

(10,)

In [10]:
b.shape

(10,)

In [11]:
a1=np.isnan(a)
b1=np.isnan(b)

In [13]:
print(a1,b1)

[False False False  True False False  True False False  True] [False False  True False  True False  True False  True False]


In [12]:
mask=a1+b1

In [14]:
mask

array([False, False,  True,  True,  True, False,  True, False,  True,
        True])

In [18]:
a2=a[~mask]
b2=b[~mask]

In [19]:
a2

array([1., 4., 5., 5.])

In [20]:
b2

array([1., 5., 5., 6.])