In [1]:
import dask.array as da
import numpy as np
import xarray as xr

In [2]:
ds1 = xr.open_dataset(r"D:\python\tianzhen\shixi3_4\ds_hgt_t_uv.nc")
ds2 = xr.open_dataset(r"D:\python\tianzhen\shixi3_4\ds_rh.nc")

In [3]:
ds1

<xarray.Dataset>
Dimensions:  (level: 12, time: 24, lat: 37, lon: 73)
Coordinates:
  * lon      (lon) float64 0.0 2.5 5.0 7.5 10.0 ... 172.5 175.0 177.5 180.0
  * lat      (lat) float64 0.0 2.5 5.0 7.5 10.0 ... 80.0 82.5 85.0 87.5 90.0
  * time     (time) datetime64[ns] 2021-07-17 ... 2021-07-22
  * level    (level) float64 1e+03 925.0 850.0 700.0 ... 250.0 200.0 150.0 100.0
Data variables:
    hgt      (level, time, lat, lon) float64 ...
    t        (level, time, lat, lon) float64 ...
    u        (level, time, lat, lon) float64 ...
    v        (level, time, lat, lon) float64 ...

In [4]:
ds2

<xarray.Dataset>
Dimensions:  (level: 8, time: 24, lat: 37, lon: 73)
Coordinates:
  * lon      (lon) float64 0.0 2.5 5.0 7.5 10.0 ... 172.5 175.0 177.5 180.0
  * lat      (lat) float64 0.0 2.5 5.0 7.5 10.0 ... 80.0 82.5 85.0 87.5 90.0
  * time     (time) datetime64[ns] 2021-07-17 ... 2021-07-22
  * level    (level) float64 1e+03 925.0 850.0 700.0 600.0 500.0 400.0 300.0
Data variables:
    rh       (level, time, lat, lon) float64 ...

In [5]:
RH = ds2['rh'][0, :, :, :]
RH

<xarray.DataArray 'rh' (time: 24, lat: 37, lon: 73)>
array([[[86., 85., ..., 83., 85.],
        [82., 79., ..., 78., 83.],
        ...,
        [99., 99., ..., 91., 91.],
        [98., 98., ..., 98., 98.]],

       [[90., 89., ..., 82., 83.],
        [89., 84., ..., 77., 80.],
        ...,
        [98., 98., ..., 91., 92.],
        [98., 98., ..., 98., 98.]],

       ...,

       [[90., 90., ..., 82., 83.],
        [83., 83., ..., 81., 82.],
        ...,
        [94., 94., ..., 85., 85.],
        [93., 93., ..., 93., 93.]],

       [[92., 91., ..., 82., 84.],
        [85., 86., ..., 85., 83.],
        ...,
        [93., 94., ..., 72., 73.],
        [88., 88., ..., 88., 88.]]])
Coordinates:
  * lon      (lon) float64 0.0 2.5 5.0 7.5 10.0 ... 172.5 175.0 177.5 180.0
  * lat      (lat) float64 0.0 2.5 5.0 7.5 10.0 ... 80.0 82.5 85.0 87.5 90.0
  * time     (time) datetime64[ns] 2021-07-17 ... 2021-07-22
    level    float64 1e+03

In [6]:
T = ds1["t"][0, :, :, :]
T=T+273.16
T

<xarray.DataArray 't' (time: 24, lat: 37, lon: 73)>
array([[[298.3, 298. , 297.3, ..., 300.9, 300.5, 300.2],
        [298.3, 298.3, 298.2, ..., 301.1, 300.9, 300.5],
        [297.7, 297.6, 297.9, ..., 301.4, 301.4, 301. ],
        ...,
        [277.2, 277.2, 277.2, ..., 277.2, 277.2, 277.2],
        [276.8, 276.8, 276.8, ..., 277.2, 277.2, 277.1],
        [276.8, 276.8, 276.8, ..., 276.8, 276.8, 276.8]],

       [[297.4, 297.2, 296.9, ..., 300.9, 300.7, 300.4],
        [297.8, 297.9, 298.1, ..., 301.3, 301.2, 300.9],
        [297.5, 297.3, 297.3, ..., 301.8, 301.8, 301.4],
        ...,
        [276.8, 276.8, 276.8, ..., 276.7, 276.7, 276.7],
        [276.5, 276.5, 276.5, ..., 276.9, 276.8, 276.8],
        [276.6, 276.6, 276.6, ..., 276.6, 276.6, 276.6]],

       [[297. , 296.8, 297.1, ..., 300.2, 300.1, 300. ],
        [297.6, 297.3, 297.5, ..., 300.9, 300.7, 300.3],
        [298. , 297.7, 297.7, ..., 301.3, 301. , 300.6],
        ...,
...
        ...,
        [275. , 275. , 275. , ..., 276.7, 276.6, 276.4],
        [274.7, 274.7, 274.8, ..., 275.8, 275.7, 275.6],
        [275. , 275. , 275. , ..., 275. , 275. , 275. ]],

       [[296.4, 296.8, 296.9, ..., 300.6, 300.4, 300.4],
        [297.6, 297.6, 297.6, ..., 300.8, 300.6, 300.5],
        [298. , 297.8, 298. , ..., 300.7, 300.5, 300.3],
        ...,
        [276.3, 276.4, 276.4, ..., 277.2, 276.9, 276.7],
        [275.8, 275.8, 275.8, ..., 276.5, 276.3, 276.2],
        [275.8, 275.8, 275.8, ..., 275.8, 275.8, 275.8]],

       [[296.3, 296.6, 297. , ..., 300.2, 299.8, 299.6],
        [297.6, 297.7, 297.9, ..., 300. , 300. , 300.1],
        [298.4, 298.1, 298.1, ..., 300. , 300.3, 300.4],
        ...,
        [276. , 276. , 275.9, ..., 278.5, 278.3, 278.2],
        [276.5, 276.5, 276.5, ..., 278.2, 278.1, 278. ],
        [277.4, 277.4, 277.4, ..., 277.4, 277.4, 277.4]]])
Coordinates:
  * lon      (lon) float64 0.0 2.5 5.0 7.5 10.0 ... 172.5 175.0 177.5 180.0
  * lat      (lat) float64 0.0 2.5 5.0 7.5 10.0 ... 80.0 82.5 85.0 87.5 90.0
  * time     (time) datetime64[ns] 2021-07-17 ... 2021-07-22
    level    float64 1e+03

In [7]:
def TDcompute(RH, T):
    import numpy as np
    es = np.zeros((RH.shape[0], RH.shape[1], RH.shape[2]))
    Td = np.zeros((RH.shape[0], RH.shape[1], RH.shape[2]))
    Ttemp = T
    a = 17.2693882
    b = 35.86
    es = 6.1078 * np.exp(a * (T - 273.16) / (T - b))
    e = es * RH / 100
    for t_i in range(RH.shape[0]):
        for i in range(RH.shape[1]):
            for j in range(RH.shape[2]):
                while e[t_i, i, j] < es[t_i, i, j]:
                    Ttemp[t_i, i, j] = Ttemp[t_i, i, j] - 0.05
                    es[t_i, i, j] = 6.1078 * \
                        np.exp(a * (Ttemp[t_i, i, j] -
                               273.16) / (Ttemp[t_i, i, j] - b))
                Td[t_i, i, j] = Ttemp[t_i, i, j]
    return Td


In [8]:
%time TDcompute(RH.data,T.data)

Wall time: 33.4 s


array([[[295.75, 295.3 , 294.4 , ..., 297.9 , 297.35, 297.45],
        [295.  , 294.35, 294.7 , ..., 297.1 , 296.7 , 297.35],
        [295.2 , 295.65, 296.5 , ..., 296.95, 296.75, 297.6 ],
        ...,
        [276.3 , 276.45, 276.45, ..., 277.05, 277.05, 277.05],
        [276.65, 276.65, 276.65, ..., 275.85, 275.85, 275.75],
        [276.5 , 276.5 , 276.5 , ..., 276.5 , 276.5 , 276.5 ]],

       [[295.65, 295.25, 294.75, ..., 297.7 , 297.3 , 297.25],
        [295.85, 295.  , 295.55, ..., 296.2 , 296.75, 297.1 ],
        [295.35, 295.9 , 296.4 , ..., 296.  , 296.2 , 297.6 ],
        ...,
        [275.75, 275.75, 275.75, ..., 276.4 , 276.4 , 276.55],
        [276.2 , 276.2 , 276.2 , ..., 275.55, 275.45, 275.6 ],
        [276.3 , 276.3 , 276.3 , ..., 276.3 , 276.3 , 276.3 ]],

       [[294.85, 294.85, 294.6 , ..., 296.85, 297.35, 298.  ],
        [295.65, 294.2 , 295.  , ..., 297.1 , 297.1 , 297.35],
        [296.75, 296.3 , 297.5 , ..., 297.05, 297.4 , 297.8 ],
        ...,
        [276

In [9]:
from dask import delayed
z=delayed(TDcompute)(RH.data,T.data)
%time z.compute()

Wall time: 29.5 s


array([[[293.25, 292.65, 291.55, ..., 295.  , 294.25, 294.75],
        [291.75, 290.55, 291.3 , ..., 293.2 , 292.6 , 294.25],
        [292.7 , 293.7 , 295.1 , ..., 292.65, 292.25, 294.3 ],
        ...,
        [275.4 , 275.7 , 275.7 , ..., 276.9 , 276.9 , 276.9 ],
        [276.5 , 276.5 , 276.5 , ..., 274.5 , 274.5 , 274.4 ],
        [276.2 , 276.2 , 276.2 , ..., 276.2 , 276.2 , 276.2 ]],

       [[293.9 , 293.35, 292.65, ..., 294.6 , 294.  , 294.15],
        [293.9 , 292.15, 293.05, ..., 291.3 , 292.45, 293.4 ],
        [293.25, 294.5 , 295.55, ..., 290.45, 290.85, 293.9 ],
        ...,
        [274.7 , 274.7 , 274.7 , ..., 276.1 , 276.1 , 276.4 ],
        [275.9 , 275.9 , 275.9 , ..., 274.2 , 274.1 , 274.4 ],
        [276.  , 276.  , 276.  , ..., 276.  , 276.  , 276.  ]],

       [[292.75, 292.95, 292.15, ..., 293.55, 294.65, 296.05],
        [293.7 , 291.2 , 292.55, ..., 293.4 , 293.6 , 294.45],
        [295.55, 294.9 , 297.3 , ..., 292.95, 293.9 , 295.1 ],
        ...,
        [275

In [10]:
import dask.array as da
RH1=da.from_array(RH.data)
T1=da.from_array(T.data)

In [11]:
RH1

dask.array<array, shape=(24, 37, 73), dtype=float64, chunksize=(24, 37, 73), chunktype=numpy.ndarray>

In [12]:
from dask import delayed
b=delayed(TDcompute)(RH1,T1)
%time b.compute()

Wall time: 26.5 s


array([[[290.8 , 290.05, 288.75, ..., 292.15, 291.2 , 292.1 ],
        [288.6 , 286.85, 287.95, ..., 289.4 , 288.65, 291.2 ],
        [290.25, 291.8 , 293.7 , ..., 288.5 , 287.9 , 291.1 ],
        ...,
        [274.5 , 274.95, 274.95, ..., 276.75, 276.75, 276.75],
        [276.35, 276.35, 276.35, ..., 273.15, 273.15, 273.05],
        [275.9 , 275.9 , 275.9 , ..., 275.9 , 275.9 , 275.9 ]],

       [[292.15, 291.45, 290.6 , ..., 291.55, 290.8 , 291.15],
        [292.  , 289.35, 290.6 , ..., 286.55, 288.3 , 289.8 ],
        [291.15, 293.1 , 294.7 , ..., 285.1 , 285.7 , 290.3 ],
        ...,
        [273.65, 273.65, 273.65, ..., 275.8 , 275.8 , 276.25],
        [275.6 , 275.6 , 275.6 , ..., 272.85, 272.8 , 273.2 ],
        [275.7 , 275.7 , 275.7 , ..., 275.7 , 275.7 , 275.7 ]],

       [[290.7 , 291.05, 289.75, ..., 290.35, 292.  , 294.1 ],
        [291.8 , 288.25, 290.1 , ..., 289.8 , 290.2 , 291.6 ],
        [294.35, 293.5 , 297.1 , ..., 289.  , 290.5 , 292.45],
        ...,
        [275

In [13]:
import pyximport
pyximport.install()

(None, <pyximport.pyximport.PyxImporter at 0x2440b0a0af0>)

In [14]:
import TDcompute
%time TDcompute.TDcompute(RH.data,T.data)

Wall time: 21.5 s


array([[[288.4 , 287.5 , 286.05, ..., 289.35, 288.25, 289.5 ],
        [285.5 , 283.25, 284.7 , ..., 285.75, 284.8 , 288.25],
        [287.85, 289.95, 292.35, ..., 284.45, 283.7 , 287.95],
        ...,
        [273.6 , 274.2 , 274.2 , ..., 276.6 , 276.6 , 276.6 ],
        [276.2 , 276.2 , 276.2 , ..., 271.85, 271.85, 271.75],
        [275.6 , 275.6 , 275.6 , ..., 275.6 , 275.6 , 275.6 ]],

       [[290.45, 289.6 , 288.55, ..., 288.6 , 287.65, 288.2 ],
        [290.1 , 286.6 , 288.2 , ..., 282.  , 284.3 , 286.3 ],
        [289.1 , 291.75, 293.85, ..., 280.  , 280.75, 286.8 ],
        ...,
        [272.65, 272.65, 272.65, ..., 275.5 , 275.5 , 276.1 ],
        [275.3 , 275.3 , 275.3 , ..., 271.55, 271.5 , 272.05],
        [275.4 , 275.4 , 275.4 , ..., 275.4 , 275.4 , 275.4 ]],

       [[288.65, 289.2 , 287.35, ..., 287.25, 289.4 , 292.2 ],
        [289.95, 285.35, 287.7 , ..., 286.3 , 286.9 , 288.8 ],
        [293.15, 292.15, 296.9 , ..., 285.15, 287.2 , 289.85],
        ...,
        [274

In [15]:
import TDcompute
from dask import delayed
b=delayed(TDcompute.TDcompute)(RH1,T1)
%time b.compute()

Wall time: 19 s


array([[[286.05, 285.  , 283.4 , ..., 286.6 , 285.35, 286.95],
        [282.5 , 279.75, 281.55, ..., 282.2 , 281.05, 285.35],
        [285.5 , 288.1 , 291.  , ..., 280.55, 279.65, 284.9 ],
        ...,
        [272.7 , 273.45, 273.45, ..., 276.45, 276.45, 276.45],
        [276.05, 276.05, 276.05, ..., 270.55, 270.55, 270.45],
        [275.3 , 275.3 , 275.3 , ..., 275.3 , 275.3 , 275.3 ]],

       [[288.75, 287.75, 286.55, ..., 285.7 , 284.6 , 285.3 ],
        [288.25, 283.95, 285.85, ..., 277.6 , 280.4 , 282.9 ],
        [287.1 , 290.4 , 293.  , ..., 275.1 , 276.  , 283.4 ],
        ...,
        [271.65, 271.65, 271.65, ..., 275.2 , 275.2 , 275.95],
        [275.  , 275.  , 275.  , ..., 270.25, 270.2 , 270.9 ],
        [275.1 , 275.1 , 275.1 , ..., 275.1 , 275.1 , 275.1 ]],

       [[286.65, 287.35, 285.  , ..., 284.2 , 286.85, 290.3 ],
        [288.1 , 282.55, 285.35, ..., 282.9 , 283.7 , 286.1 ],
        [291.95, 290.8 , 296.7 , ..., 281.4 , 283.95, 287.3 ],
        ...,
        [274